# Jekyll configuration for Vertex Documentation
title: Vertex Documentation
description: IMU Cycling Data Analysis Platform - Technical Documentation
baseurl: ""
url: "https://hawthorne-ben.github.io"

# Build settings
markdown: kramdown
highlighter: rouge
theme: minima

# Site settings
author: Ben Hawthorne
email: hawthorneben@gmail.com

# Navigation
navigation:
  - title: Overview
    url: /
  - title: Architecture
    url: /architecture/
  - title: Development
    url: /development/
  - title: Features
    url: /features/
  - title: Operations
    url: /operations/
  - title: API Reference
    url: /api-reference/

# Collections for better organization
collections:
  architecture:
    output: true
    permalink: /:collection/:name/
  development:
    output: true
    permalink: /:collection/:name/
  features:
    output: true
    permalink: /:collection/:name/
  operations:
    output: true
    permalink: /:collection/:name/
  api-reference:
    output: true
    permalink: /:collection/:name/

# Exclude from processing
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - .sass-cache
  - .jekyll-cache
  - .jekyll-metadata

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# SEO
seo:
  type: WebSite
  name: Vertex Documentation
  description: Technical documentation for Vertex IMU cycling data analysis platform
