# Jekyll configuration for Vertex Documentation
title: Vertex Documentation
description: IMU Cycling Data Analysis Platform - Technical Documentation
baseurl: "/vertex"
url: "https://hawthorne-ben.github.io"

# Build settings
markdown: kramdown
highlighter: rouge
theme: minima

# Site settings
author: Ben Hawthorne
email: hawthorneben@gmail.com

# Navigation for minima theme
header_pages:
  - architecture/index.md
  - development/index.md
  - features/index.md
  - operations/index.md
  - api-reference/index.md

# Exclude from processing
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - .sass-cache
  - .jekyll-cache
  - .jekyll-metadata

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
